//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class OnlineSchoolEntities : DbContext
{
    public OnlineSchoolEntities()
        : base("name=OnlineSchoolEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<AbsenceAlert> AbsenceAlerts { get; set; }
    public DbSet<AbsenceDecision> AbsenceDecisions { get; set; }
    public DbSet<Absence> Absences { get; set; }
    public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
    public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
    public DbSet<aspnet_Users> aspnet_Users { get; set; }
    public DbSet<Attendence> Attendences { get; set; }
    public DbSet<Book> Books { get; set; }
    public DbSet<BorrowsofEmployee> BorrowsofEmployees { get; set; }
    public DbSet<BorrowsofStudent> BorrowsofStudents { get; set; }
    public DbSet<ChangeLog> ChangeLogs { get; set; }
    public DbSet<ChemistryCupboard> ChemistryCupboards { get; set; }
    public DbSet<Communication> Communications { get; set; }
    public DbSet<Constant> Constants { get; set; }
    public DbSet<ConstantsType> ConstantsTypes { get; set; }
    public DbSet<Councile> Counciles { get; set; }
    public DbSet<CouncilMember> CouncilMembers { get; set; }
    public DbSet<DailyShift> DailyShifts { get; set; }
    public DbSet<EmployeesVacation> EmployeesVacations { get; set; }
    public DbSet<EmployeeWaiting> EmployeeWaitings { get; set; }
    public DbSet<EventLogged> EventLoggeds { get; set; }
    public DbSet<ExpensesProgram> ExpensesPrograms { get; set; }
    public DbSet<Experience> Experiences { get; set; }
    public DbSet<Grades1> Grades1 { get; set; }
    public DbSet<Grades2> Grades2 { get; set; }
    public DbSet<Grades3> Grades3 { get; set; }
    public DbSet<Grades4> Grades4 { get; set; }
    public DbSet<Grades5> Grades5 { get; set; }
    public DbSet<Grades6> Grades6 { get; set; }
    public DbSet<GuidProgram> GuidPrograms { get; set; }
    public DbSet<HelpStudent> HelpStudents { get; set; }
    public DbSet<IncentivesForEmployee> IncentivesForEmployees { get; set; }
    public DbSet<Incoming> Incomings { get; set; }
    public DbSet<IncomingsImage> IncomingsImages { get; set; }
    public DbSet<Job> Jobs { get; set; }
    public DbSet<LaboratoriesInventory> LaboratoriesInventories { get; set; }
    public DbSet<Laboratory> Laboratories { get; set; }
    public DbSet<LatenessAlert> LatenessAlerts { get; set; }
    public DbSet<LatenessDecision> LatenessDecisions { get; set; }
    public DbSet<Lateness> Latenesses { get; set; }
    public DbSet<LibraryClassVisit> LibraryClassVisits { get; set; }
    public DbSet<LibraryDailyVisit> LibraryDailyVisits { get; set; }
    public DbSet<Material> Materials { get; set; }
    public DbSet<Message> Messages { get; set; }
    public DbSet<MissingMaterial> MissingMaterials { get; set; }
    public DbSet<Notification> Notifications { get; set; }
    public DbSet<Obligation> Obligations { get; set; }
    public DbSet<Outcoming> Outcomings { get; set; }
    public DbSet<OutstandingStudent> OutstandingStudents { get; set; }
    public DbSet<PermissionAlert> PermissionAlerts { get; set; }
    public DbSet<PermissionGroup> PermissionGroups { get; set; }
    public DbSet<Permission> Permissions { get; set; }
    public DbSet<PermissionsClass> PermissionsClasses { get; set; }
    public DbSet<Profile> Profiles { get; set; }
    public DbSet<Purchase> Purchases { get; set; }
    public DbSet<Repository> Repositories { get; set; }
    public DbSet<Required> Requireds { get; set; }
    public DbSet<Revenue> Revenues { get; set; }
    public DbSet<Schedual> Scheduals { get; set; }
    public DbSet<SchoolFund> SchoolFunds { get; set; }
    public DbSet<SchoolResourceBox> SchoolResourceBoxes { get; set; }
    public DbSet<School> Schools { get; set; }
    public DbSet<Semester> Semesters { get; set; }
    public DbSet<Setting> Settings { get; set; }
    public DbSet<StudentActivity> StudentActivities { get; set; }
    public DbSet<StudentPatient> StudentPatients { get; set; }
    public DbSet<Student> Students { get; set; }
    public DbSet<StudentsAbsence> StudentsAbsences { get; set; }
    public DbSet<StudentsAttendence> StudentsAttendences { get; set; }
    public DbSet<StudentsGuide> StudentsGuides { get; set; }
    public DbSet<StudentsInActivity> StudentsInActivities { get; set; }
    public DbSet<StudentsLateness> StudentsLatenesses { get; set; }
    public DbSet<StudentsNote> StudentsNotes { get; set; }
    public DbSet<StudentsPermission> StudentsPermissions { get; set; }
    public DbSet<StudentsSubject> StudentsSubjects { get; set; }
    public DbSet<StudentsViolation> StudentsViolations { get; set; }
    public DbSet<Subject> Subjects { get; set; }
    public DbSet<SubjectsInSemester> SubjectsInSemesters { get; set; }
    public DbSet<SubjectTable> SubjectTables { get; set; }
    public DbSet<SupportStudent> SupportStudents { get; set; }
    public DbSet<Task> Tasks { get; set; }
    public DbSet<Teacher> Teachers { get; set; }
    public DbSet<TeachersSubject> TeachersSubjects { get; set; }
    public DbSet<UsersGeneralization> UsersGeneralizations { get; set; }
    public DbSet<UsersTask> UsersTasks { get; set; }
    public DbSet<Violation> Violations { get; set; }
    public DbSet<ViolationsAction> ViolationsActions { get; set; }
    public DbSet<ViolationsActionsForm> ViolationsActionsForms { get; set; }
    public DbSet<Visit> Visits { get; set; }
    public DbSet<Week> Weeks { get; set; }
    public DbSet<Employee> Employees { get; set; }
}
