//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Absence
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string EmployeeId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<int> Type { get; set; }
    public Nullable<int> AlertId { get; set; }
}

public partial class AbsenceAlert
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<System.DateTime> DateFrom { get; set; }
    public Nullable<System.DateTime> DateTo { get; set; }
    public Nullable<System.DateTime> AlertDate { get; set; }
    public string Reason { get; set; }
    public Nullable<System.DateTime> ReplyDate { get; set; }
    public string Decision { get; set; }
    public Nullable<System.DateTime> DecisionDate { get; set; }
    public string EmployeeId { get; set; }
    public Nullable<int> count { get; set; }
    public Nullable<int> countHoliday { get; set; }
    public bool IsPrinted { get; set; }
}

public partial class AbsenceDecision
{
    public int Id { get; set; }
    public string AbsenceAlertId { get; set; }
}

public partial class aspnet_Membership
{
    public System.Guid ApplicationId { get; set; }
    public System.Guid UserId { get; set; }
    public string Password { get; set; }
    public int PasswordFormat { get; set; }
    public string PasswordSalt { get; set; }
    public string MobilePIN { get; set; }
    public string Email { get; set; }
    public string LoweredEmail { get; set; }
    public string PasswordQuestion { get; set; }
    public string PasswordAnswer { get; set; }
    public bool IsApproved { get; set; }
    public bool IsLockedOut { get; set; }
    public System.DateTime CreateDate { get; set; }
    public System.DateTime LastLoginDate { get; set; }
    public System.DateTime LastPasswordChangedDate { get; set; }
    public System.DateTime LastLockoutDate { get; set; }
    public int FailedPasswordAttemptCount { get; set; }
    public System.DateTime FailedPasswordAttemptWindowStart { get; set; }
    public int FailedPasswordAnswerAttemptCount { get; set; }
    public System.DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }
    public string Comment { get; set; }

    public virtual aspnet_Users aspnet_Users { get; set; }
}

public partial class aspnet_Roles
{
    public aspnet_Roles()
    {
        this.PermissionGroups = new HashSet<PermissionGroup>();
        this.aspnet_Users = new HashSet<aspnet_Users>();
    }

    public System.Guid ApplicationId { get; set; }
    public System.Guid RoleId { get; set; }
    public string RoleName { get; set; }
    public string LoweredRoleName { get; set; }
    public string Description { get; set; }
    public string GroupName { get; set; }

    public virtual ICollection<PermissionGroup> PermissionGroups { get; set; }
    public virtual ICollection<aspnet_Users> aspnet_Users { get; set; }
}

public partial class aspnet_Users
{
    public aspnet_Users()
    {
        this.aspnet_Roles = new HashSet<aspnet_Roles>();
    }

    public System.Guid ApplicationId { get; set; }
    public System.Guid UserId { get; set; }
    public string UserName { get; set; }
    public string LoweredUserName { get; set; }
    public string MobileAlias { get; set; }
    public bool IsAnonymous { get; set; }
    public System.DateTime LastActivityDate { get; set; }

    public virtual aspnet_Membership aspnet_Membership { get; set; }
    public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }
}

public partial class Attendence
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string EmployeeId { get; set; }
    public Nullable<System.TimeSpan> ArrivingTime { get; set; }
    public Nullable<System.TimeSpan> DepartureTime { get; set; }
}

public partial class Book
{
    public int Id { get; set; }
    public string BookId { get; set; }
    public int SchoolId { get; set; }
    public string Title { get; set; }
    public string Auther { get; set; }
    public Nullable<int> TotalNumber { get; set; }
    public Nullable<int> AvailableNumber { get; set; }
}

public partial class BorrowsofEmployee
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<int> BookId { get; set; }
    public string EmployeeId { get; set; }
    public Nullable<System.DateTime> DateBorrow { get; set; }
    public Nullable<System.DateTime> DateReturn { get; set; }
    public Nullable<bool> isReturn { get; set; }
    public Nullable<System.DateTime> DateEmployeeReturn { get; set; }
}

public partial class BorrowsofStudent
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<int> BookId { get; set; }
    public string StudentId { get; set; }
    public Nullable<System.DateTime> DateBorrow { get; set; }
    public Nullable<System.DateTime> DateReturn { get; set; }
    public Nullable<bool> isReturn { get; set; }
    public Nullable<System.DateTime> DateStudentReturn { get; set; }
}

public partial class ChangeLog
{
    public int Id { get; set; }
    public string EntityName { get; set; }
    public string PropertyName { get; set; }
    public string PrimaryKeyValue { get; set; }
    public string OldValue { get; set; }
    public string NewValue { get; set; }
    public Nullable<System.DateTime> DateChanged { get; set; }
}

public partial class ChemistryCupboard
{
    public int Id { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> CupboardId { get; set; }
    public Nullable<int> KindId { get; set; }
    public string KindName { get; set; }
    public string Unit { get; set; }
    public Nullable<int> Quantity { get; set; }
    public string Comments { get; set; }
}

public partial class Communication
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string ContactNo { get; set; }
    public Nullable<System.TimeSpan> Time { get; set; }
    public string Reason { get; set; }
    public string Reply { get; set; }
}

public partial class Constant
{
    public int Id { get; set; }
    public string value { get; set; }
    public Nullable<int> type { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public bool isDeleted { get; set; }
}

public partial class ConstantsType
{
    public int Id { get; set; }
    public string Type { get; set; }
    public Nullable<bool> IsDynamic { get; set; }
    public string DefaultVal { get; set; }
}

public partial class Councile
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string FileLocation { get; set; }
}

public partial class CouncilMember
{
    public int Id { get; set; }
    public Nullable<int> CouncilId { get; set; }
    public string EmployeeId { get; set; }
    public string Title { get; set; }
}

public partial class DailyShift
{
    public int Id { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<bool> IsSupervisor { get; set; }
    public Nullable<bool> IsAlternate { get; set; }
    public string Note { get; set; }
    public string TeacherID { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
}

public partial class Employee
{
    public Nullable<int> No { get; set; }
    public string IdentityNumber { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public string Name { get; set; }
    public string Nationality { get; set; }
    public Nullable<System.DateTime> IdentityDate { get; set; }
    public string Qualification { get; set; }
    public string YearofQualification { get; set; }
    public string Specification { get; set; }
    public string JobNumber { get; set; }
    public Nullable<System.DateTime> JobStartMinistry { get; set; }
    public Nullable<System.DateTime> JobStartSchool { get; set; }
    public Nullable<System.DateTime> JobStartCurrent { get; set; }
    public string Level { get; set; }
    public string Degree { get; set; }
    public string PhoneHome { get; set; }
    public string Mobile { get; set; }
    public string Email { get; set; }
    public string Comments { get; set; }
    public string classesNumber { get; set; }
    public Nullable<int> JobId { get; set; }

    public virtual Job Job { get; set; }
    public virtual School School { get; set; }
}

public partial class EmployeesVacation
{
    public string EmployeeId { get; set; }
    public Nullable<int> Year { get; set; }
    public Nullable<int> VacationNumber { get; set; }
}

public partial class EmployeeWaiting
{
    public int Id { get; set; }
    public Nullable<int> AbsenceId { get; set; }
    public string EmployeeId { get; set; }
    public Nullable<int> Period { get; set; }
    public string ClassRoom { get; set; }
    public string Subject { get; set; }
    public string Do { get; set; }
    public string Comment { get; set; }
}

public partial class EventLogged
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string DayExecution { get; set; }
    public Nullable<System.DateTime> DateExecution { get; set; }
    public Nullable<System.TimeSpan> TimeExecution { get; set; }
    public string LocationExecution { get; set; }
    public Nullable<int> GeneralizationNo { get; set; }
    public string Image { get; set; }
    public Nullable<int> EventType { get; set; }
    public string Description { get; set; }
    public string Required { get; set; }
    public string Responsible { get; set; }
    public Nullable<bool> Presence { get; set; }
}

public partial class ExpensesProgram
{
    public int Id { get; set; }
    public string ProgramName { get; set; }
    public Nullable<int> Price { get; set; }
    public string Description { get; set; }
    public Nullable<int> BillNumber { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<int> Rest { get; set; }
    public string Note { get; set; }
    public Nullable<int> SchoolId { get; set; }
}

public partial class Experience
{
    public int Id { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public string Class { get; set; }
    public string Subject { get; set; }
    public string Name { get; set; }
    public string BookName { get; set; }
    public string BookPage { get; set; }
    public Nullable<int> Week { get; set; }
    public string Tools { get; set; }
    public string TeacherId { get; set; }
}

public partial class Grades1
{
    public int Id { get; set; }
    public string StudentId { get; set; }
    public Nullable<int> SubjectId { get; set; }
    public Nullable<double> WrittingQuiz { get; set; }
    public Nullable<double> PracticalQuiz { get; set; }
    public Nullable<double> Reports { get; set; }
    public Nullable<double> Activities { get; set; }
    public Nullable<double> Homeworks { get; set; }
    public Nullable<double> Works { get; set; }
    public Nullable<double> FinalWritting { get; set; }
    public Nullable<double> FinalPractical { get; set; }
    public Nullable<double> Attendence { get; set; }
    public Nullable<double> Total { get; set; }
}

public partial class Grades2
{
    public int Id { get; set; }
    public string StudentId { get; set; }
    public Nullable<int> SubjectId { get; set; }
    public Nullable<double> Projects { get; set; }
    public Nullable<double> Works { get; set; }
    public Nullable<double> Activities { get; set; }
    public Nullable<double> Homeworks { get; set; }
    public Nullable<double> Quiz1 { get; set; }
    public Nullable<double> Quiz2 { get; set; }
    public Nullable<double> Final { get; set; }
    public Nullable<double> Attendence { get; set; }
    public Nullable<double> Total { get; set; }
}

public partial class Grades3
{
    public int Id { get; set; }
    public string StudentId { get; set; }
    public Nullable<int> SubjectId { get; set; }
    public Nullable<double> WrittingQuiz { get; set; }
    public Nullable<double> Research { get; set; }
    public Nullable<double> Activities { get; set; }
    public Nullable<double> Homeworks { get; set; }
    public Nullable<double> Works { get; set; }
    public Nullable<double> FinalWritting { get; set; }
    public Nullable<double> Attendence { get; set; }
    public Nullable<double> Total { get; set; }
}

public partial class Grades4
{
    public int Id { get; set; }
    public string StudentId { get; set; }
    public Nullable<int> SubjectId { get; set; }
    public Nullable<double> Final { get; set; }
    public Nullable<double> Attendence { get; set; }
    public Nullable<double> Total { get; set; }
}

public partial class Grades5
{
    public int Id { get; set; }
    public string StudentId { get; set; }
    public Nullable<int> SubjectId { get; set; }
    public Nullable<double> Fluency { get; set; }
    public Nullable<double> Reading { get; set; }
    public Nullable<double> Saving { get; set; }
    public Nullable<double> practice { get; set; }
    public Nullable<double> Correctness { get; set; }
    public Nullable<double> Attendence { get; set; }
    public Nullable<double> Total { get; set; }
}

public partial class Grades6
{
    public int Id { get; set; }
    public string StudentId { get; set; }
    public Nullable<int> SubjectId { get; set; }
    public Nullable<double> Fitness { get; set; }
    public Nullable<double> Skills { get; set; }
    public Nullable<double> Achievement { get; set; }
    public Nullable<double> Knowledge { get; set; }
    public Nullable<double> Homeworks { get; set; }
    public Nullable<double> Attendence { get; set; }
    public Nullable<double> Total { get; set; }
}

public partial class GuidProgram
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string ProgramName { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public string Occasion { get; set; }
    public Nullable<int> BeneficiariesNo { get; set; }
    public Nullable<int> StudentNo { get; set; }
    public string Responsiveness { get; set; }
    public Nullable<int> BeneficiariesType { get; set; }
}

public partial class HelpStudent
{
    public int Id { get; set; }
    public string StudentId { get; set; }
    public Nullable<bool> Price { get; set; }
    public string Class { get; set; }
    public Nullable<int> Rest { get; set; }
    public string Note { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<int> SchoolId { get; set; }
}

public partial class IncentivesForEmployee
{
    public int Id { get; set; }
    public string EmloyeeId { get; set; }
    public string Value { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<int> Rest { get; set; }
    public string Note { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
}

public partial class Incoming
{
    public int Id { get; set; }
    public string Number { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<int> Source { get; set; }
    public string Subject { get; set; }
    public string FileNumber { get; set; }
    public Nullable<int> Type { get; set; }
    public Nullable<int> Attachment { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
    public string FileLocation { get; set; }
    public string Comment { get; set; }
}

public partial class IncomingsImage
{
    public int Id { get; set; }
    public Nullable<int> IncomingId { get; set; }
    public string Image { get; set; }
}

public partial class Job
{
    public Job()
    {
        this.Employees = new HashSet<Employee>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string FileLocation { get; set; }

    public virtual ICollection<Employee> Employees { get; set; }
}

public partial class LaboratoriesInventory
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string KindName { get; set; }
    public Nullable<int> KindId { get; set; }
    public string Unit { get; set; }
    public Nullable<int> ValidCount { get; set; }
    public Nullable<int> NotValidCount { get; set; }
    public Nullable<int> ObligatedCount { get; set; }
    public Nullable<int> Increase { get; set; }
}

public partial class Laboratory
{
    public int Id { get; set; }
    public Nullable<int> KindId { get; set; }
    public string KindName { get; set; }
    public string Unit { get; set; }
    public Nullable<int> Quantity { get; set; }
    public string Comment { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
}

public partial class Lateness
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string EmployeeId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<int> Type { get; set; }
    public Nullable<System.TimeSpan> Amount { get; set; }
    public Nullable<double> TotalSeconds { get; set; }
    public Nullable<System.TimeSpan> TimeFrom { get; set; }
    public Nullable<System.TimeSpan> Timeto { get; set; }
    public bool IsPrinted { get; set; }
    public Nullable<System.DateTime> AlertDate { get; set; }
}

public partial class LatenessAlert
{
    public int Id { get; set; }
    public Nullable<int> LatenessId { get; set; }
    public string Reason { get; set; }
    public Nullable<bool> isAccepted { get; set; }
    public Nullable<System.DateTime> ReplyDate { get; set; }
    public Nullable<System.DateTime> AcceptDate { get; set; }
}

public partial class LatenessDecision
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string EmployeeId { get; set; }
    public Nullable<int> Days { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<int> Hours { get; set; }
    public Nullable<bool> IsPrinted { get; set; }
}

public partial class LibraryClassVisit
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<int> Period { get; set; }
    public Nullable<int> SubjectId { get; set; }
    public string TeacherId { get; set; }
    public Nullable<bool> IsDone { get; set; }
}

public partial class LibraryDailyVisit
{
    public int Id { get; set; }
    public int SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string StudentId { get; set; }
    public string Reason { get; set; }
    public string MaterialsUsed { get; set; }
    public Nullable<System.TimeSpan> Time { get; set; }
}

public partial class Material
{
    public int Id { get; set; }
    public Nullable<int> KindId { get; set; }
    public string KindName { get; set; }
    public Nullable<int> Quantity { get; set; }
    public string Comments { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<int> Status { get; set; }
}

public partial class Message
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<System.TimeSpan> Time { get; set; }
    public string Reason { get; set; }
    public string Person { get; set; }
}

public partial class MissingMaterial
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<int> KindId { get; set; }
    public string KindName { get; set; }
    public Nullable<bool> IsPerminant { get; set; }
    public string Unit { get; set; }
    public Nullable<int> Quantity { get; set; }
    public string Reason { get; set; }
    public string Comments { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
}

public partial class Notification
{
    public int Id { get; set; }
    public string Text { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public string EmployeeId { get; set; }
    public Nullable<bool> isSeen { get; set; }
    public Nullable<int> Type { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string URL { get; set; }
}

public partial class Obligation
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string KindName { get; set; }
    public Nullable<int> Count { get; set; }
    public string EmployeeId { get; set; }
    public Nullable<System.DateTime> DateReceive { get; set; }
    public string EmployeeReturn { get; set; }
    public Nullable<System.DateTime> DateReturn { get; set; }
    public string Comments { get; set; }
    public Nullable<bool> IsReceived { get; set; }
    public Nullable<bool> IsReturn { get; set; }
}

public partial class Outcoming
{
    public int Id { get; set; }
    public string Number { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<int> SourceFrom { get; set; }
    public Nullable<int> SourceTo { get; set; }
    public string Subject { get; set; }
    public string Text { get; set; }
    public string FileNumber { get; set; }
    public Nullable<int> Type { get; set; }
    public Nullable<int> Attachment { get; set; }
    public Nullable<System.DateTime> ReceivedDate { get; set; }
    public string ReceivedName { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
    public string FileLocation { get; set; }
    public string FileLocation2 { get; set; }
}

public partial class OutstandingStudent
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string StudentId { get; set; }
    public Nullable<bool> Price { get; set; }
    public string Class { get; set; }
    public string FieldExcellence { get; set; }
    public string Note { get; set; }
}

public partial class Permission
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string EmployeeId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<System.TimeSpan> TimeFrom { get; set; }
    public Nullable<System.TimeSpan> TimeTo { get; set; }
    public string Reason { get; set; }
    public string Comments { get; set; }
    public string MahramName { get; set; }
    public string MahramRelation { get; set; }
    public Nullable<int> MahramIdentity { get; set; }
    public Nullable<double> TotalSeconds { get; set; }
    public bool IsPrinted { get; set; }
}

public partial class PermissionAlert
{
    public int Id { get; set; }
    public Nullable<int> PermissionId { get; set; }
    public string Reason { get; set; }
    public Nullable<bool> isAccepted { get; set; }
    public Nullable<System.DateTime> AlertDate { get; set; }
    public Nullable<System.DateTime> ReplyDate { get; set; }
    public Nullable<System.DateTime> AcceptDate { get; set; }
    public Nullable<bool> IsPrinted { get; set; }
}

public partial class PermissionGroup
{
    public int PId { get; set; }
    public string PGroupName { get; set; }
    public Nullable<System.Guid> RoleId { get; set; }

    public virtual aspnet_Roles aspnet_Roles { get; set; }
}

public partial class PermissionsClass
{
    public int Id { get; set; }
    public string PermissionEmployeeId { get; set; }
    public string EmployeeId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<int> Period { get; set; }
    public string ClassRoom { get; set; }
    public string Comment { get; set; }
    public string Reason { get; set; }
}

public partial class Profile
{
    public string Id { get; set; }
    public string Name { get; set; }
    public string Image { get; set; }
}

public partial class Purchase
{
    public int Id { get; set; }
    public Nullable<int> ItemId { get; set; }
    public Nullable<int> UnitPrice { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<int> TotalPrice { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string BillSide { get; set; }
    public Nullable<int> BillNumber { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<int> SchoolId { get; set; }
}

public partial class Repository
{
    public int Id { get; set; }
    public int KindId { get; set; }
    public string KindName { get; set; }
    public string Description { get; set; }
    public Nullable<bool> IsDamaged { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<bool> IsPerminant { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string Comment { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
}

public partial class Required
{
    public int Id { get; set; }
    public Nullable<int> ItemID { get; set; }
    public Nullable<int> Price { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<int> SchoolId { get; set; }
}

public partial class Revenue
{
    public int Id { get; set; }
    public Nullable<int> Price { get; set; }
    public Nullable<System.DateTime> ReceiveDate { get; set; }
    public string RecipientsName { get; set; }
    public Nullable<int> TypeId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> deliveryType { get; set; }
}

public partial class Schedual
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> type { get; set; }
    public string Name { get; set; }
    public Nullable<System.TimeSpan> Time { get; set; }
    public Nullable<System.TimeSpan> Period { get; set; }
}

public partial class School
{
    public School()
    {
        this.Employees = new HashSet<Employee>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string logo { get; set; }
    public Nullable<int> NumberOfSecretary { get; set; }
    public Nullable<int> Type { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
    public string Area { get; set; }
    public Nullable<int> Gender { get; set; }
    public System.TimeSpan TimeStartWork { get; set; }
    public System.TimeSpan TimeEndWork { get; set; }
    public int VacationNumber { get; set; }
    public string OutcomingCode { get; set; }
    public string StatisticaFigure { get; set; }
    public string EducationalLevel { get; set; }
    public string Office { get; set; }
    public string Address { get; set; }
    public string ThePhone { get; set; }
    public string Email { get; set; }
    public Nullable<int> TotalClass { get; set; }
    public Nullable<int> TotalStudents { get; set; }
    public Nullable<int> TotalStaff { get; set; }
    public Nullable<int> RentedBuildingsNo { get; set; }
    public Nullable<int> GovernmentBuildingsNo { get; set; }
    public string YearFounded { get; set; }
    public Nullable<bool> IsDateHijri { get; set; }

    public virtual ICollection<Employee> Employees { get; set; }
}

public partial class SchoolFund
{
    public int Id { get; set; }
    public Nullable<int> MeetingNo { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string Recommendations { get; set; }
    public string HeadQuarters { get; set; }
    public string Description { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
}

public partial class SchoolResourceBox
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<int> TypeId { get; set; }
    public Nullable<int> Price { get; set; }
    public Nullable<int> Total { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string Note { get; set; }
}

public partial class Semester
{
    public int Id { get; set; }
    public Nullable<int> Semester1 { get; set; }
    public Nullable<int> YearH { get; set; }
    public Nullable<int> YearM { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public Nullable<bool> IsCurrent { get; set; }
}

public partial class Setting
{
    public string KKey { get; set; }
    public string KVal { get; set; }
    public string Title { get; set; }
    public string Group { get; set; }
    public string DefaultValue { get; set; }
}

public partial class Student
{
    public Nullable<int> Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public string Name { get; set; }
    public string NameEnglish { get; set; }
    public string Nationality { get; set; }
    public string NationalityEnglish { get; set; }
    public string Specification { get; set; }
    public string YearofEntry { get; set; }
    public string IdentityNumber { get; set; }
    public string IdentityType { get; set; }
    public Nullable<System.DateTime> IdentityDate { get; set; }
    public string PassportNumber { get; set; }
    public Nullable<System.DateTime> DOB { get; set; }
    public string Record { get; set; }
    public string ConstraintState { get; set; }
    public Nullable<System.DateTime> DateOfStart { get; set; }
    public string Comment { get; set; }
    public string IdentitySource { get; set; }
    public string EducationalLevel { get; set; }
    public Nullable<int> Semester { get; set; }
    public string Class { get; set; }
    public Nullable<int> ResidencyNo { get; set; }
    public string CountryBirth { get; set; }
    public string CityBirth { get; set; }
    public string BloodType { get; set; }
    public string AdministrativeRegion { get; set; }
    public string City { get; set; }
    public string District { get; set; }
    public string MainStreet { get; set; }
    public string SubStreet { get; set; }
    public string HouseNo { get; set; }
    public string OwnershipHousing { get; set; }
    public string Email { get; set; }
    public string PostalCode { get; set; }
    public string MailBox { get; set; }
    public string Fax { get; set; }
    public string AddressHoliday { get; set; }
    public string GuardianName { get; set; }
    public string GuardianNationality { get; set; }
    public string RelativeRelation { get; set; }
    public string GuardianIdentityType { get; set; }
    public Nullable<System.DateTime> DateIdentity { get; set; }
    public string GuardianIdentitySource { get; set; }
    public Nullable<System.DateTime> EndIdentity { get; set; }
    public string HomePhoneNo { get; set; }
    public string MobileNumber { get; set; }
    public string WorkPhoneNumber { get; set; }
    public string NameStudentClose1 { get; set; }
    public string MobileClose1 { get; set; }
    public string AddressClose1 { get; set; }
    public string NameStudentClose { get; set; }
    public string MobileClose { get; set; }
    public string AddressClose { get; set; }
}

public partial class StudentActivity
{
    public int Id { get; set; }
    public string FieldName { get; set; }
    public string Activity { get; set; }
    public string Seat { get; set; }
    public Nullable<System.DateTime> DateFrom { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<System.DateTime> DateTo { get; set; }
}

public partial class StudentPatient
{
    public int Id { get; set; }
    public string StudentId { get; set; }
    public string Class { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string HomeTel { get; set; }
    public string Description { get; set; }
    public string Action { get; set; }
    public string Recommendations { get; set; }
    public string WorkTel { get; set; }
    public string Mobile { get; set; }
}

public partial class StudentsAbsence
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string StudentId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string Reason { get; set; }
    public Nullable<bool> IsExcuse { get; set; }
    public Nullable<bool> IsOneDay { get; set; }
    public Nullable<System.DateTime> DateTo { get; set; }
}

public partial class StudentsAttendence
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string StudentId { get; set; }
    public Nullable<System.TimeSpan> ArrivingTime { get; set; }
    public Nullable<System.TimeSpan> DepartureTime { get; set; }
}

public partial class StudentsGuide
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string GuidName { get; set; }
    public string StudentNumber { get; set; }
    public string StudentName { get; set; }
    public string Year { get; set; }
}

public partial class StudentsInActivity
{
    public int Id { get; set; }
    public int ActiviteId { get; set; }
    public string StudentId { get; set; }
    public Nullable<bool> Saturday { get; set; }
    public Nullable<bool> Sunday { get; set; }
    public Nullable<bool> Monday { get; set; }
    public Nullable<bool> Tuesday { get; set; }
    public Nullable<bool> Wednesday { get; set; }
}

public partial class StudentsLateness
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string StudentId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<int> Type { get; set; }
    public Nullable<System.TimeSpan> Amount { get; set; }
    public Nullable<double> TotalSeconds { get; set; }
    public string Class { get; set; }
    public string Reason { get; set; }
}

public partial class StudentsNote
{
    public int Id { get; set; }
    public string StudentId { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public string TeacherId { get; set; }
    public string Note { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
}

public partial class StudentsPermission
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string StudentId { get; set; }
    public string Class { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<System.TimeSpan> TimeFrom { get; set; }
    public string Reason { get; set; }
    public string Comments { get; set; }
    public string ParentName { get; set; }
}

public partial class StudentsSubject
{
    public int Id { get; set; }
    public string StudentId { get; set; }
    public Nullable<int> SubjectId { get; set; }
    public string Rate { get; set; }
}

public partial class StudentsViolation
{
    public int Id { get; set; }
    public string StudentId { get; set; }
    public Nullable<int> ViolationId { get; set; }
    public Nullable<int> Count { get; set; }
    public string TeacherId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
}

public partial class Subject
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Nullable<int> Type { get; set; }
}

public partial class SubjectsInSemester
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<int> SubjectId { get; set; }
    public string ClassId { get; set; }
    public string TeacherId { get; set; }
}

public partial class SubjectTable
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> subjectId { get; set; }
    public Nullable<int> Day { get; set; }
    public string Period1 { get; set; }
    public string Period2 { get; set; }
    public string Period3 { get; set; }
    public string Period4 { get; set; }
    public string Period5 { get; set; }
    public string Period6 { get; set; }
    public string Period7 { get; set; }
    public string Period8 { get; set; }
}

public partial class SupportStudent
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<int> BillNo { get; set; }
    public Nullable<int> Price { get; set; }
    public string Note { get; set; }
    public string Contents { get; set; }
}

public partial class Task
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public Nullable<int> IncommingId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<System.DateTime> DateAlarm { get; set; }
    public Nullable<int> TypeId { get; set; }
    public string Location { get; set; }
    public string EmployeeId { get; set; }
    public Nullable<bool> IsStudentRequired { get; set; }
    public Nullable<bool> IsEmployeeRequired { get; set; }
}

public partial class Teacher
{
    public string IdentityNumber { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public string Name { get; set; }
    public string BirthLocation { get; set; }
    public Nullable<System.DateTime> BirthDate { get; set; }
    public string Status { get; set; }
    public string Sons { get; set; }
    public string SonsYounger6 { get; set; }
    public string SonsYounger24 { get; set; }
    public string SonsOLder24 { get; set; }
    public string Email { get; set; }
    public string MailBox { get; set; }
    public string PostalCode { get; set; }
    public string Mobile { get; set; }
    public string Telephon1 { get; set; }
    public string Telephon2 { get; set; }
    public string Address { get; set; }
}

public partial class TeachersSubject
{
    public int Id { get; set; }
    public string TeacherId { get; set; }
    public Nullable<int> SubjectId { get; set; }
    public string Class { get; set; }
}

public partial class UsersGeneralization
{
    public string UserId { get; set; }
    public int IncomingId { get; set; }
    public Nullable<bool> isSeen { get; set; }
}

public partial class UsersTask
{
    public int Id { get; set; }
    public string UserId { get; set; }
    public int TaskId { get; set; }
    public Nullable<bool> IsEmployee { get; set; }
}

public partial class Violation
{
    public int Id { get; set; }
    public string Title { get; set; }
    public Nullable<int> Grade { get; set; }
}

public partial class ViolationsAction
{
    public int Id { get; set; }
    public Nullable<int> Grade { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public Nullable<int> Count { get; set; }
}

public partial class ViolationsActionsForm
{
    public int Id { get; set; }
    public string Form { get; set; }
    public Nullable<int> ViolationActionId { get; set; }
}

public partial class Visit
{
    public int Id { get; set; }
    public Nullable<int> SchoolId { get; set; }
    public Nullable<int> SemesterId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string Reason { get; set; }
    public string Name { get; set; }
    public string StudentId { get; set; }
}

public partial class Week
{
    public int Id { get; set; }
    public Nullable<System.DateTime> startDate { get; set; }
    public Nullable<int> type { get; set; }
    public string Name { get; set; }
}
